//! `get_about` command — engine/algo/RNG identity plus the scope disclaimer.
//!
//! All values are read from `clinrand_core` constants. Nothing here touches the
//! filesystem: the disclaimer is hard-coded (see [`DISCLAIMER`]) rather than
//! read from `README.md` at runtime.

use clinrand_core::{ALGO_VERSION, ENGINE_VERSION, RNG_CRATE_VERSION};
use serde::Serialize;

/// Scope disclaimer surfaced on the About screen.
///
/// Substance of the README § Scope statement (plan §14): ClinRand is not a
/// certified system and responsibility for a list rests with the approving
/// statistician. Hard-coded here so the running app never reads `README.md`.
const DISCLAIMER: &str =
    "ClinRand generates randomization lists and the evidence needed to review \
them. It is not a certified computerised system and produces no approved artifact on its own. A \
list generated by ClinRand must be independently QC'd and formally approved by a qualified \
unblinded statistician before any use in a clinical trial. The QC procedure and the evidence \
under validation/ exist to make that review possible; responsibility for the list rests with the \
statistician who approves it, not with the software.";

/// About information: versions, RNG identity, and the scope disclaimer.
#[derive(Clone, Debug, Serialize)]
pub struct AboutInfo {
    /// `clinrand-core` crate version (`ENGINE_VERSION`).
    pub engine_version: String,
    /// Algorithm-contract version (`ALGO_VERSION`). Currently `1`.
    pub algo_version: u32,
    /// RNG algorithm identity used in the allocation path.
    pub rng_algorithm: String,
    /// RNG crate name (`rand_chacha`).
    pub rng_crate: String,
    /// Pinned `rand_chacha` version (`RNG_CRATE_VERSION`).
    pub rng_crate_version: String,
    /// Scope disclaimer text (plan §14).
    pub disclaimer: String,
}

/// Return engine/algorithm/RNG identity and the scope disclaimer.
#[tauri::command]
pub fn get_about() -> AboutInfo {
    AboutInfo {
        engine_version: ENGINE_VERSION.to_string(),
        algo_version: ALGO_VERSION,
        rng_algorithm: "ChaCha20".to_string(),
        rng_crate: "rand_chacha".to_string(),
        rng_crate_version: RNG_CRATE_VERSION.to_string(),
        disclaimer: DISCLAIMER.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::get_about;

    #[test]
    fn reports_algo_version_one_and_rng_identity() {
        let about = get_about();
        assert_eq!(about.algo_version, 1);
        assert_eq!(about.rng_crate, "rand_chacha");
        assert_eq!(about.rng_algorithm, "ChaCha20");
        assert_eq!(about.rng_crate_version, "0.3.1");
        assert!(!about.engine_version.is_empty());
    }

    #[test]
    fn disclaimer_is_non_empty_and_mentions_statistician_responsibility() {
        let about = get_about();
        assert!(!about.disclaimer.is_empty());
        assert!(about.disclaimer.contains("not a certified"));
        assert!(about.disclaimer.contains("statistician"));
    }
}
