//! Blinded and unblinded HTML generation reports (plan §6.5).
//!
//! Hand-rolled `format!` HTML — no templating crate. The blinded report must
//! never pair a randomization number with an arm code, and must never include
//! the seed.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use clinrand_core::{
    check_properties, stratum_combinations, AllocationRecord, BlockScheme, GeneratedList, Method,
    NumberingScheme, StudyConfig, ALGO_VERSION,
};

use crate::manifest::PackageMeta;

/// File digests embedded in both HTML reports (plan §6.5).
///
/// Covers the data/manifest files written beside the reports. Self-hashes of
/// the HTML files are recorded only in `checksums.txt`, not here (circular).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ReportFileHashes {
    /// SHA-256 of `list.csv` UTF-8 bytes.
    pub list_sha256: String,
    /// SHA-256 of `list.json` UTF-8 bytes.
    pub list_json_sha256: String,
    /// SHA-256 of `stream.csv` UTF-8 bytes.
    pub stream_sha256: String,
    /// SHA-256 of `manifest.blinded.json` UTF-8 bytes.
    pub manifest_blinded_sha256: String,
    /// SHA-256 of `manifest.unblinded.json` UTF-8 bytes.
    pub manifest_unblinded_sha256: String,
    /// SHA-256 of canonical config JSON.
    pub config_sha256: String,
    /// SHA-256 of the raw 32 seed bytes (never the seed itself).
    pub seed_sha256: String,
}

/// Render `generation-report.html` (blinded).
///
/// Includes study metadata, full config (arms+ratios, not assignments),
/// per-stratum counts and block structure (canonical stratum order, including
/// zero-count strata), hashes, engine/algo versions, [`check_properties`]
/// id/status only (no detail text), and truncation / numbering warnings.
///
/// Does **not** include the seed, any randomization-number↔arm pairing,
/// per-block arm composition, or raw property-check detail strings.
pub fn render_generation_report(
    cfg: &StudyConfig,
    list: &GeneratedList,
    meta: &PackageMeta,
    hashes: &ReportFileHashes,
) -> String {
    let properties = check_properties(list, cfg);
    let mut body = String::new();

    push_header(&mut body, "ClinRand generation report (blinded)");
    push_meta_section(&mut body, cfg, meta);
    push_config_section(&mut body, cfg);
    push_counts_section(&mut body, cfg, list);
    push_block_structure_section(&mut body, cfg, list);
    push_truncation_section(&mut body, cfg, list);
    push_numbering_warning(&mut body, cfg);
    push_hashes_section(&mut body, hashes);
    push_versions_section(&mut body);
    push_properties_section(&mut body, &properties, /* include_details */ false);
    push_footer(&mut body);

    wrap_html("ClinRand generation report (blinded)", &body)
}

/// Render `unblinded-report.html` (restricted).
///
/// May include the full randomization-number ↔ arm list. Still never writes
/// the seed (seed lives only in `manifest.unblinded.json`).
pub fn render_unblinded_report(
    cfg: &StudyConfig,
    list: &GeneratedList,
    meta: &PackageMeta,
    hashes: &ReportFileHashes,
) -> String {
    let properties = check_properties(list, cfg);
    let mut body = String::new();

    push_header(&mut body, "ClinRand generation report (unblinded)");
    push_meta_section(&mut body, cfg, meta);
    push_config_section(&mut body, cfg);
    push_counts_section(&mut body, cfg, list);
    push_block_structure_section(&mut body, cfg, list);
    push_truncation_section(&mut body, cfg, list);
    push_numbering_warning(&mut body, cfg);
    push_hashes_section(&mut body, hashes);
    push_versions_section(&mut body);
    push_properties_section(&mut body, &properties, /* include_details */ true);
    push_allocation_table(&mut body, cfg, list);
    push_footer(&mut body);

    wrap_html("ClinRand generation report (unblinded)", &body)
}

fn wrap_html(title: &str, body: &str) -> String {
    format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>{title}</title>\n</head>\n<body>\n{body}</body>\n</html>\n",
        title = escape_html(title),
        body = body
    )
}

fn push_header(out: &mut String, heading: &str) {
    let _ = writeln!(out, "<h1>{}</h1>", escape_html(heading));
}

fn push_footer(out: &mut String) {
    let _ = writeln!(
        out,
        "<p>This report is generated by ClinRand. The blinded report must not be used as an allocation list.</p>"
    );
}

fn push_meta_section(out: &mut String, cfg: &StudyConfig, meta: &PackageMeta) {
    let _ = writeln!(out, "<h2>Study</h2>");
    let _ = writeln!(out, "<ul>");
    let _ = writeln!(out, "<li>study_id: {}</li>", escape_html(&cfg.study_id));
    let _ = writeln!(
        out,
        "<li>protocol_version: {}</li>",
        escape_html(&cfg.protocol_version)
    );
    let _ = writeln!(
        out,
        "<li>generated_at: {}</li>",
        escape_html(&meta.generated_at)
    );
    let _ = writeln!(out, "<li>operator: {}</li>", escape_html(&meta.operator));
    let _ = writeln!(out, "</ul>");
}

fn push_config_section(out: &mut String, cfg: &StudyConfig) {
    let _ = writeln!(out, "<h2>Configuration</h2>");

    let _ = writeln!(out, "<h3>Arms and ratios</h3>");
    let _ = writeln!(out, "<ul>");
    for arm in &cfg.arms {
        // Arm codes appear only in this section of the blinded report —
        // never on the same line as a randomization number.
        let _ = writeln!(
            out,
            "<li>arm_code={} label={} ratio={}</li>",
            escape_html(&arm.code),
            escape_html(&arm.label),
            arm.ratio
        );
    }
    let _ = writeln!(out, "</ul>");

    let _ = writeln!(out, "<h3>Method and blocks</h3>");
    let _ = writeln!(out, "<ul>");
    match &cfg.method {
        Method::Simple => {
            let _ = writeln!(out, "<li>method: simple</li>");
            let _ = writeln!(out, "<li>block: none</li>");
        }
        Method::PermutedBlock { block } => {
            let _ = writeln!(out, "<li>method: permuted_block</li>");
            push_block_scheme_li(out, block);
        }
        Method::StratifiedBlock { block } => {
            let _ = writeln!(out, "<li>method: stratified_block</li>");
            push_block_scheme_li(out, block);
        }
    }
    let _ = writeln!(out, "</ul>");

    let _ = writeln!(out, "<h3>Strata</h3>");
    if cfg.strata.is_empty() {
        let _ = writeln!(out, "<p>No stratification factors.</p>");
    } else {
        let _ = writeln!(out, "<ul>");
        for factor in &cfg.strata {
            let levels: Vec<String> = factor.levels.iter().map(|l| escape_html(l)).collect();
            let _ = writeln!(
                out,
                "<li>factor={} levels=[{}]</li>",
                escape_html(&factor.name),
                levels.join(", ")
            );
        }
        let _ = writeln!(out, "</ul>");
    }

    let _ = writeln!(out, "<h3>Numbering</h3>");
    let _ = writeln!(out, "<ul>");
    match cfg.numbering {
        NumberingScheme::Global { start, width } => {
            let _ = writeln!(out, "<li>kind=global start={start} width={width}</li>");
        }
        NumberingScheme::PerStratumRange {
            start,
            block_size,
            width,
        } => {
            let _ = writeln!(
                out,
                "<li>kind=per_stratum_range start={start} block_size={block_size} width={width}</li>"
            );
        }
    }
    let _ = writeln!(
        out,
        "<li>list_length_per_stratum: {}</li>",
        cfg.list_length_per_stratum
    );
    let _ = writeln!(out, "</ul>");
}

fn push_block_scheme_li(out: &mut String, block: &BlockScheme) {
    match block {
        BlockScheme::Fixed { size } => {
            let _ = writeln!(out, "<li>block: fixed size={size}</li>");
        }
        BlockScheme::Variable { sizes } => {
            let sizes_s: Vec<String> = sizes.iter().map(|s| s.to_string()).collect();
            let _ = writeln!(
                out,
                "<li>block: variable sizes=[{}]</li>",
                sizes_s.join(", ")
            );
        }
    }
}

fn push_counts_section(out: &mut String, cfg: &StudyConfig, list: &GeneratedList) {
    let _ = writeln!(out, "<h2>Record counts</h2>");
    let _ = writeln!(out, "<p>total_records: {}</p>", list.records.len());

    let _ = writeln!(out, "<h3>Per stratum</h3>");
    let _ = writeln!(out, "<ul>");
    if cfg.strata.is_empty() {
        let _ = writeln!(out, "<li>(unstratified) count={}</li>", list.records.len());
    } else {
        match stratum_combinations(&cfg.strata) {
            Ok(combos) => {
                for combo in &combos {
                    let label = stratum_label(cfg, combo);
                    let count = list.records.iter().filter(|r| &r.stratum == combo).count();
                    // Intentionally no randomization numbers and no arm codes here.
                    // Canonical config order (plan §5.4), including count=0 strata.
                    let _ = writeln!(
                        out,
                        "<li>stratum={} count={}</li>",
                        escape_html(&label),
                        count
                    );
                }
            }
            Err(_) => {
                let _ = writeln!(out, "<li>stratum combination count overflowed</li>");
            }
        }
    }
    let _ = writeln!(out, "</ul>");
}

fn push_block_structure_section(out: &mut String, cfg: &StudyConfig, list: &GeneratedList) {
    let _ = writeln!(out, "<h2>Block structure</h2>");
    let _ = writeln!(out, "<p>Counts and sizes only — no arm composition.</p>");
    let _ = writeln!(out, "<ul>");

    if cfg.strata.is_empty() {
        let size_counts = block_size_counts_for_stratum(list, &BTreeMap::new());
        if size_counts.is_empty() {
            let _ = writeln!(out, "<li>no blocks</li>");
        } else {
            let _ = writeln!(
                out,
                "<li>stratum=(unstratified) blocks: {}</li>",
                format_block_size_counts(&size_counts)
            );
        }
    } else {
        match stratum_combinations(&cfg.strata) {
            Ok(combos) => {
                for combo in &combos {
                    let label = stratum_label(cfg, combo);
                    let size_counts = block_size_counts_for_stratum(list, combo);
                    let blocks = if size_counts.is_empty() {
                        "(none)".to_owned()
                    } else {
                        format_block_size_counts(&size_counts)
                    };
                    let _ = writeln!(
                        out,
                        "<li>stratum={} blocks: {}</li>",
                        escape_html(&label),
                        blocks
                    );
                }
            }
            Err(_) => {
                let _ = writeln!(out, "<li>stratum combination count overflowed</li>");
            }
        }
    }
    let _ = writeln!(out, "</ul>");
}

fn push_truncation_section(out: &mut String, cfg: &StudyConfig, list: &GeneratedList) {
    let _ = writeln!(out, "<h2>Truncation</h2>");
    let warnings = truncation_warnings(cfg, list);
    if warnings.is_empty() {
        let _ = writeln!(out, "<p>No truncated final blocks.</p>");
        return;
    }
    let _ = writeln!(out, "<ul>");
    for w in warnings {
        let _ = writeln!(out, "<li>{}</li>", escape_html(&w));
    }
    let _ = writeln!(out, "</ul>");
}

fn push_numbering_warning(out: &mut String, cfg: &StudyConfig) {
    if matches!(cfg.numbering, NumberingScheme::PerStratumRange { .. }) {
        let _ = writeln!(out, "<h2>Numbering disclosure warning</h2>");
        let _ = writeln!(
            out,
            "<p>per_stratum_range numbering discloses stratum membership from the randomization number alone. Prefer global numbering unless reserved ranges are deliberately required.</p>"
        );
    }
}

fn push_hashes_section(out: &mut String, hashes: &ReportFileHashes) {
    // Each hash on its own line with no arm codes — blind-safety: a hex digest
    // may coincidentally contain a randomization-number substring.
    let _ = writeln!(out, "<h2>Hashes</h2>");
    let _ = writeln!(out, "<ul>");
    let _ = writeln!(
        out,
        "<li>config_sha256: {}</li>",
        escape_html(&hashes.config_sha256)
    );
    let _ = writeln!(
        out,
        "<li>seed_sha256: {}</li>",
        escape_html(&hashes.seed_sha256)
    );
    let _ = writeln!(
        out,
        "<li>list_sha256: {}</li>",
        escape_html(&hashes.list_sha256)
    );
    let _ = writeln!(
        out,
        "<li>list_json_sha256: {}</li>",
        escape_html(&hashes.list_json_sha256)
    );
    let _ = writeln!(
        out,
        "<li>stream_sha256: {}</li>",
        escape_html(&hashes.stream_sha256)
    );
    let _ = writeln!(
        out,
        "<li>manifest_blinded_sha256: {}</li>",
        escape_html(&hashes.manifest_blinded_sha256)
    );
    let _ = writeln!(
        out,
        "<li>manifest_unblinded_sha256: {}</li>",
        escape_html(&hashes.manifest_unblinded_sha256)
    );
    let _ = writeln!(out, "</ul>");
}

fn push_versions_section(out: &mut String) {
    let engine_version = env!("CARGO_PKG_VERSION");
    let _ = writeln!(out, "<h2>Versions</h2>");
    let _ = writeln!(out, "<ul>");
    let _ = writeln!(
        out,
        "<li>engine_version: {}</li>",
        escape_html(engine_version)
    );
    let _ = writeln!(out, "<li>algo_version: {ALGO_VERSION}</li>");
    let _ = writeln!(out, "</ul>");
}

fn push_properties_section(
    out: &mut String,
    report: &clinrand_core::PropertyReport,
    include_details: bool,
) {
    let _ = writeln!(out, "<h2>Property checks</h2>");
    let overall = if report.all_required_passed() {
        "all required checks passed"
    } else {
        "one or more required checks failed"
    };
    let _ = writeln!(out, "<p>{}</p>", escape_html(overall));
    let _ = writeln!(out, "<ul>");
    for check in &report.checks {
        let status = if check.informational {
            if check.passed {
                "informational"
            } else {
                "informational (unexpected fail)"
            }
        } else if check.passed {
            "PASS"
        } else {
            "FAIL"
        };
        // Blinded report: id + pass/fail (+ informational) only. Full detail
        // text can name a randomization number and an arm (P03/P04/P09/P10)
        // and belongs only in the unblinded report.
        let _ = writeln!(
            out,
            "<li>{} {}</li>",
            escape_html(check.id),
            escape_html(status)
        );
        if include_details {
            let _ = writeln!(out, "<li>detail: {}</li>", escape_html(&check.detail));
        }
    }
    let _ = writeln!(out, "</ul>");
}

fn push_allocation_table(out: &mut String, cfg: &StudyConfig, list: &GeneratedList) {
    let _ = writeln!(out, "<h2>Allocations (unblinded)</h2>");
    let _ = writeln!(out, "<table>");
    let _ = write!(out, "<tr><th>randomization_number</th>");
    for factor in &cfg.strata {
        let _ = write!(out, "<th>{}</th>", escape_html(&factor.name));
    }
    let _ = writeln!(
        out,
        "<th>block_id</th><th>block_size</th><th>position_in_block</th><th>arm_code</th></tr>"
    );
    for rec in &list.records {
        let _ = write!(
            out,
            "<tr><td>{}</td>",
            escape_html(&rec.randomization_number)
        );
        for factor in &cfg.strata {
            let level = rec
                .stratum
                .get(&factor.name)
                .map(String::as_str)
                .unwrap_or("");
            let _ = write!(out, "<td>{}</td>", escape_html(level));
        }
        let _ = writeln!(
            out,
            "<td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            rec.block_id,
            rec.block_size,
            rec.position_in_block,
            escape_html(&rec.arm_code)
        );
    }
    let _ = writeln!(out, "</table>");
}

/// Escape text for HTML element content / attributes.
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn stratum_label(cfg: &StudyConfig, stratum: &BTreeMap<String, String>) -> String {
    if cfg.strata.is_empty() {
        return "(unstratified)".into();
    }
    let mut parts = Vec::with_capacity(cfg.strata.len());
    for factor in &cfg.strata {
        let level = stratum.get(&factor.name).map(String::as_str).unwrap_or("?");
        parts.push(format!("{}={}", factor.name, level));
    }
    parts.join(", ")
}

/// Map of block_size → number of distinct block_ids with that size, for one stratum.
fn block_size_counts_for_stratum(
    list: &GeneratedList,
    stratum: &BTreeMap<String, String>,
) -> BTreeMap<u32, u32> {
    let mut blocks: BTreeMap<u32, u32> = BTreeMap::new();
    for rec in &list.records {
        if &rec.stratum == stratum {
            blocks.entry(rec.block_id).or_insert(rec.block_size);
        }
    }
    let mut size_counts: BTreeMap<u32, u32> = BTreeMap::new();
    for size in blocks.values() {
        *size_counts.entry(*size).or_insert(0) += 1;
    }
    size_counts
}

fn format_block_size_counts(size_counts: &BTreeMap<u32, u32>) -> String {
    let mut parts = Vec::new();
    for (size, n_blocks) in size_counts {
        parts.push(format!("{n_blocks}×size {size}"));
    }
    parts.join(", ")
}

fn truncation_warnings(cfg: &StudyConfig, list: &GeneratedList) -> Vec<String> {
    let mut max_ids: BTreeMap<&BTreeMap<String, String>, u32> = BTreeMap::new();
    for rec in &list.records {
        max_ids
            .entry(&rec.stratum)
            .and_modify(|m| *m = (*m).max(rec.block_id))
            .or_insert(rec.block_id);
    }

    let mut groups: BTreeMap<(BTreeMap<String, String>, u32), Vec<&AllocationRecord>> =
        BTreeMap::new();
    for rec in &list.records {
        groups
            .entry((rec.stratum.clone(), rec.block_id))
            .or_default()
            .push(rec);
    }

    let mut warnings = Vec::new();
    for ((stratum, block_id), members) in groups {
        let Some(first) = members.first() else {
            continue;
        };
        let kept = members.len() as u32;
        if kept < first.block_size && max_ids.get(&stratum) == Some(&block_id) {
            let label = stratum_label(cfg, &stratum);
            warnings.push(format!(
                "truncated final block in stratum {label}: block_id={block_id} kept={kept} of block_size={}",
                first.block_size
            ));
        }
    }
    warnings
}
